#!/bin/bash
set -e
set -u
set -o pipefail

PYTHON=$HOME/src/pypy-2.0-beta1/bin/pypy

CODE="$1.py"

if [ ! -e "$CODE" ]; then
    echo "[----] Code doesn't exist $CODE"
    exit
fi

NO=
for NOTRY in `seq 0 1000`; do
    if [ ! -e "$1-$2-$NOTRY.in" ]; then
        break
    fi
    NO="$NOTRY"
done

IN=$1-$2-$NO.in
OUT=$1-$2-$NO.out

if [ ! -e "$IN" ]; then
    echo "[----] Input $IN doesn't exist!"
    exit
fi

if [ -e "$OUT" ]; then
    mv $OUT $OUT.bak
fi

ulimit -s 9000000
echo "[****] COUNTING....."
/usr/bin/time -f "%E real" $PYTHON $CODE < $IN > $OUT
echo "[****] Uploading $OUT"
gcj_submit_solution.py -a $CODE $1 $2 $NO
